apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xstorageaccounts.storage.example.io
  labels:
    provider: azure
    type: standard
spec:
  compositeTypeRef:
    apiVersion: storage.example.io/v1alpha1
    kind: XStorageAccount
  
  mode: Pipeline
  pipeline:
  - step: patch-and-transform
    functionRef:
      name: function-patch-and-transform
    input:
      apiVersion: pt.fn.crossplane.io/v1beta1
      kind: Resources
      resources:
      # NOTE:
      # This example uses the cluster-scoped Upbound Azure API groups (without `.m.`).
      # If you prefer namespaced managed resources, use the `.m.upbound.io` API groups
      # and ensure the corresponding CRDs are installed.

      - name: resourcegroup
        base:
          apiVersion: azure.upbound.io/v1beta1
          kind: ResourceGroup
          spec:
            forProvider:
              location: westeurope
              tags:
                managedBy: crossplane
                environment: test
        patches:
        - type: FromCompositeFieldPath
          fromFieldPath: spec.parameters.location
          toFieldPath: spec.forProvider.location
        - type: FromCompositeFieldPath
          fromFieldPath: spec.parameters.resourceGroupName
          toFieldPath: metadata.name

      - name: storageaccount
        base:
          apiVersion: storage.azure.upbound.io/v1beta2
          kind: Account
          metadata:
            annotations:
              # Azure Storage Account names must be lowercase letters+numbers only (no dashes).
              # For a real setup, generate a unique name. This example uses a fixed name.
              crossplane.io/external-name: teststoragee2e001
          spec:
            forProvider:
              accountReplicationType: LRS
              accountTier: Standard
              resourceGroupName: crossplane-e2e-test-rg
              tags:
                managedBy: crossplane
                environment: test
        patches:
        - type: FromCompositeFieldPath
          fromFieldPath: spec.parameters.location
          toFieldPath: spec.forProvider.location
        - type: FromCompositeFieldPath
          fromFieldPath: spec.parameters.accountTier
          toFieldPath: spec.forProvider.accountTier
        - type: FromCompositeFieldPath
          fromFieldPath: spec.parameters.replicationType
          toFieldPath: spec.forProvider.accountReplicationType
        - type: FromCompositeFieldPath
          fromFieldPath: spec.parameters.resourceGroupName
          toFieldPath: spec.forProvider.resourceGroupName
        - type: FromCompositeFieldPath
          fromFieldPath: metadata.name
          toFieldPath: metadata.name
        - type: ToCompositeFieldPath
          fromFieldPath: metadata.annotations[crossplane.io/external-name]
          toFieldPath: status.storageAccountName
        - type: ToCompositeFieldPath
          fromFieldPath: status.atProvider.primaryBlobEndpoint
          toFieldPath: status.primaryEndpoint
        readinessChecks:
        - type: MatchString
          fieldPath: status.atProvider.provisioningState
          matchString: Succeeded
  
  - step: auto-ready
    functionRef:
      name: function-auto-ready
