apiVersion: apiextensions.crossplane.io/v2
kind: CompositeResourceDefinition
metadata:
  name: xstorageaccounts.storage.example.io
spec:
  group: storage.example.io
  names:
    kind: XStorageAccount
    plural: xstorageaccounts
  # NOTE (Crossplane v2):
  # - In Crossplane v2.x, XRDs use `apiVersion: apiextensions.crossplane.io/v2`.
  # - This `apiVersion` is the CRD API version for the XRD type (not the XR's API version).
  # - Crossplane v2 uses XRs (Composite Resources). Claims are not used in this guide.
  scope: Namespaced
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              parameters:
                type: object
                properties:
                  location:
                    type: string
                    description: Azure region for the storage account
                    default: westeurope
                  accountTier:
                    type: string
                    description: Storage account tier
                    enum: [Standard, Premium]
                    default: Standard
                  replicationType:
                    type: string
                    description: Replication type
                    enum: [LRS, GRS, RAGRS, ZRS]
                    default: LRS
                  resourceGroupName:
                    type: string
                    description: Azure resource group name
                  tags:
                    type: object
                    description: Additional tags for the storage account
                    additionalProperties:
                      type: string
                required:
                - resourceGroupName
            required:
            - parameters
          status:
            type: object
            properties:
              storageAccountName:
                type: string
              primaryEndpoint:
                type: string
