apiVersion: apiextensions.crossplane.io/v2
kind: CompositeResourceDefinition
metadata:
  name: xstorageaccounts.storage.example.io
spec:
  group: storage.example.io
  names:
    kind: XStorageAccount
    plural: xstorageaccounts
  # NOTE (Crossplane v2):
  # - Crossplane v2 introduces the XRD `apiextensions.crossplane.io/v2` API.
  # - The v2 XRD API adds the `scope` field (defaults to Namespaced). We set it explicitly.
  # - This guide uses XRs (Composite Resources) directly (no Claims).
  # NOTE:
  # Upbound Azure Storage Accounts are currently exposed as cluster-scoped managed resources
  # (`storage.azure.upbound.io/...`). A namespaced XR cannot compose cluster-scoped resources.
  # Therefore this example uses a cluster-scoped XR.
  scope: Cluster
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              # Crossplane v2-style XR "machinery" fields live under `spec.crossplane`.
              # We include the parts we use (composition selection).
              crossplane:
                type: object
                properties:
                  compositionSelector:
                    type: object
                    properties:
                      matchLabels:
                        type: object
                        additionalProperties:
                          type: string
              parameters:
                type: object
                properties:
                  location:
                    type: string
                    description: Azure region for the storage account
                    default: westeurope
                  accountTier:
                    type: string
                    description: Storage account tier
                    enum: [Standard, Premium]
                    default: Standard
                  replicationType:
                    type: string
                    description: Replication type
                    enum: [LRS, GRS, RAGRS, ZRS]
                    default: LRS
                  resourceGroupName:
                    type: string
                    description: Azure resource group name
                  tags:
                    type: object
                    description: Additional tags for the storage account
                    additionalProperties:
                      type: string
                required:
                - resourceGroupName
            required:
            - parameters
          status:
            type: object
            properties:
              storageAccountName:
                type: string
              primaryEndpoint:
                type: string
