---

apiVersion: devopstoolkitseries.com/v1alpha1
kind: SQLClaim
metadata:
  name: cncf-demo
spec:
  id: cncf-demo-db-dev
  compositionSelector:
    matchLabels:
      provider: local-k8s
      db: postgresql
  parameters:
    version: "13.4"
    size: small
  # Crossplane v2: composite resources no longer have native connection details support.
  # Don't rely on claim/XR-level `writeConnectionSecretToRef`; instead compose your own
  # connection Secret (or use External Secrets Operator) as described in the docs.
